### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by jdehn** [fusioninventory/fusioninventory-agent-windows-installer#1] opened 2018-05-18 07:57 UTC
Hi there!
I am trying to install the agent on my Windows 10 Pro machines (1703, 1709 and 1803) but I am getting the same issue like described [here](https://github.com/fusioninventory/fusioninventory-agent/issues/141).

`fusioninventory-agent_windows-x64_2.4.exe /acceptlicense /no-start-menu /server='http://xxx/glpi/plugins/fusioninventory/' /runnow /execmode=service /installtype=from-scratch /installtasks=inventory,deploy `

If I try that the installer will start and I have to choose the language but after clicking "OK" the User's Guide is opened.
If I try the same thing with "/S" nothing happens.

Does anyone else get this behaviour still in version 2.4?

Thanks a lot!

**Comment by gabrielranulfo** [comment] 2018-06-19 12:23
Hello, I have a problem with the Vbs script that I use to install the client, instead of searching for the executable in GitHub according to Destination, I changed it to my local server

For some reason, the previously configured Git server did not work, use it as a palliative solution until it resolves or corrects the script

![image](https://user-images.githubusercontent.com/31252711/41596827-ea607e5a-73a1-11e8-9664-a00e97c670b1.png)

**Comment by ddurieux** [comment] 2018-06-19 12:28
perhaps remove the _& SetupVersion_ if you put the file directly in _/download/_ on your web server

**Comment by g-bougard** [comment] 2018-06-19 13:13
@jdehn 
This happens only when one of your argument is wrong. Can you double-check your command line ?
I think by the way the installer should first tell what is wrong than just open the help page.

**Comment by jdehn** [comment] 2018-07-02 14:27
@g-bougard 
Thank you for your reply - I checked the arguments again and I can't see anything wrong.
After a while playing around I found out the setup works properly without the server-argument.
`/server='http://server.dom.ain/glpi/plugins/fusioninventory/'`

Could you tell me if that is wrong? Also tried it without quotes and with double qoutes, nothing happens.

**Comment by jdehn** [comment] 2018-08-06 07:38
Error still not solved - is anyone reading this?

**Comment by ddurieux** [comment] 2018-08-06 07:45
Try use `"` instead `'` because I think it get the word `/server` in the URL and use it as an argument

**Comment by jdehn** [comment] 2018-08-06 14:16
Setup is working now but I can't start the service because of "[error] No target defined, aborting".

So that is still not the solution for this problem - do you have another idea?

**Comment by ddurieux** [comment] 2018-08-06 15:34
for the arguments, it's in the file vbs or you run the install command on cmd / powrshell command?

**Comment by jdehn** [comment] 2018-08-07 06:37
I am running that via batch script and deploying it via group policy - poorly there is no msi package.

**Comment by ddurieux** [comment] 2018-08-07 07:03
So why not use the `vbs` file? it works perfectly with GPO deployement

**Comment by jdehn** [comment] 2018-08-08 07:59
Sure, I could switch to vbs and have to learn how vbs works - but why can't I just use the commandline?

Is there or will there be a solution for this problem?

**Comment by Wolvverine** [comment] 2018-10-03 09:42
The same problem.
The reason for this was to use ' instead of " in
/server="http://server1/plugin/fusioninventory,http://server2/plugin/fusioninventory,..."
 then the installer displays the guide.
IMHO transferring to instructions without any error messages is not a good idea.

The second case of firing the Powershell console even the correct command will result in the same without any information about where the problem is.

**Comment by g-bougard** [comment] 2018-10-12 10:33
Hi there,

the windows installer was a little modified in 2.4.2 to show a combo box when it detects an error on command line parsing. **The combox appears even if run in silent mode**... Sorry, I didn't find a better way by now. But I decided this is still better than nothing and this should really help people having trouble finding the right parameters combination.

This may be a problem if people is publishing with wrong parameters to a lot of machine at the same time. So always test your parameters before publishing !

With this feature added, I'm closing this issue as I think people will now know why the silent install fails thanks to the combo.

**Closed as completed by g-bougard** 2018-10-12 10:33 UTC

**Comment by mariopmio** [comment] 2025-05-15 14:27
No arquivo glpi-agent.cfg habilite:    local = /tmp
